### ISSUE TITLE
Контроллер под круд

### ISSUE THREAD

**Issue by mmargullan** [mmargullan/rk#6]
Надо создать рест контроллер для управления юзерами, задай маппинг "/manage" для нового контроллера, там организуй круд операции, это чисто для вида нужно

**Comment by GitFisherBait** [comment]
Это надо сделать с юзерами которые залогинились или можно по простому своих юзеров добавлять?

**Comment by mmargullan** [comment]
Юзеры которые в базе сохраняются когда авторизуются

**Comment by GitFisherBait** [comment]
Ок, тогда сделано. Пока вывожу данные в постмане

**Comment by mmargullan** [comment]
Отлично, пуш изменения на новую ветку и отправляй пр, я рассмотрю

**Comment by K4444R** [comment]
я сделал круд с тасками


мне мерджить?
